### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by kubilaycaglayan** [kubilaycaglayan/Ruby-on-Rails-Capstone-Project-Twitter#5]
When users try to upload a photo with a size greater than 1MB, they should get proper feedback about validation.

**Comment by mariosknl** [comment]
Great project Kubilay. I liked the new feature you added with Javascript. Thank you for presenting it to us.

**Comment by frankopkusianwar** [comment]
Good job kubilay. As a suggestion, you could try to alert the user with a message when validating file size. with all my respect
